import path from "node:path";
import fs from "fs-extra";
import type { BoxRecord, PiBoxConfig } from "../core/types.js";

export const PI_AGENT_DIR_IN_CONTAINER = "/workspace/.boxedagent/pi-agent";
export const PI_PROJECT_DIR_IN_CONTAINER = "/workspace/.pi";
const RPC_STDIO_GUARD_FILENAME = "rpc-stdio-guard.cjs";
const RPC_STDIO_GUARD_IN_CONTAINER = `${PI_AGENT_DIR_IN_CONTAINER}/${RPC_STDIO_GUARD_FILENAME}`;

export function piRuntimeEnv(box: BoxRecord, options: { stdioGuard?: boolean } = {}): string[] {
  const env = [
    `PI_CODING_AGENT_DIR=${PI_AGENT_DIR_IN_CONTAINER}`,
    "PI_SKIP_VERSION_CHECK=1",
    "PI_TELEMETRY=0",
    "PATH=/usr/local/bin:/opt/nvm/versions/node/v22.22.2/bin:/opt/nvm/versions/node/v22/bin:/opt/nvm/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  ];
  if (options.stdioGuard ?? true) env.push(`NODE_OPTIONS=${nodeOptionsWithRpcStdioGuard(box.env?.NODE_OPTIONS)}`);
  return env;
}

export function mergePiSettings(pi: PiBoxConfig): Record<string, unknown> {
  const settings: Record<string, unknown> = {
    quietStartup: true,
    enableInstallTelemetry: false,
    compaction: { enabled: true, reserveTokens: 16384, keepRecentTokens: 20000 },
    retry: { enabled: true, maxRetries: 3, baseDelayMs: 2000, maxDelayMs: 60000 },
    steeringMode: "one-at-a-time",
    followUpMode: "one-at-a-time",
    ...(pi.settingsJson ?? {})
  };
  if (pi.defaultProvider) settings.defaultProvider = pi.defaultProvider;
  if (pi.defaultModel) settings.defaultModel = pi.defaultModel;
  if (pi.defaultThinkingLevel) settings.defaultThinkingLevel = pi.defaultThinkingLevel;
  if (pi.enabledModels?.length) settings.enabledModels = pi.enabledModels;
  settings.sessionDir = "/workspace/.pi-sessions";
  return settings;
}

export async function materializeBoxPiConfig(box: BoxRecord): Promise<void> {
  const pi = box.pi ?? {};
  const agentDir = path.join(box.workspacePath, ".boxedagent", "pi-agent");
  const projectPiDir = path.join(box.workspacePath, ".pi");
  await fs.ensureDir(agentDir);
  await fs.ensureDir(projectPiDir);
  await fs.ensureDir(path.join(box.workspacePath, ".pi-sessions"));

  const settingsPath = path.join(agentDir, "settings.json");
  const existingSettings = await fs.readJson(settingsPath).catch(() => ({})) as Record<string, unknown>;
  const nextSettings = mergePiSettings(pi);
  for (const key of ["packages", "extensions", "skills", "prompts", "themes", "npmCommand"] as const) {
    if (nextSettings[key] === undefined && existingSettings[key] !== undefined) nextSettings[key] = existingSettings[key];
  }
  await fs.writeJson(settingsPath, nextSettings, { spaces: 2 });

  if (pi.modelsJson && Object.keys(pi.modelsJson).length > 0) {
    await fs.writeJson(path.join(agentDir, "models.json"), pi.modelsJson, { spaces: 2 });
  } else {
    await fs.remove(path.join(agentDir, "models.json"));
  }

  await fs.writeFile(path.join(agentDir, RPC_STDIO_GUARD_FILENAME), RPC_STDIO_GUARD_SCRIPT, "utf8");
  await writeOrRemove(path.join(agentDir, "AGENTS.md"), pi.agentsMd);
  await writeOrRemove(path.join(projectPiDir, "SYSTEM.md"), pi.systemPrompt);
  await writeOrRemove(path.join(projectPiDir, "APPEND_SYSTEM.md"), pi.appendSystemPrompt);
}

function nodeOptionsWithRpcStdioGuard(existing?: string): string {
  const value = existing?.trim() ?? "";
  if (value.includes(RPC_STDIO_GUARD_IN_CONTAINER)) return value;
  return [value, "--require", RPC_STDIO_GUARD_IN_CONTAINER].filter(Boolean).join(" ");
}

const RPC_STDIO_GUARD_SCRIPT = String.raw`// Generated by BoxedAgent. Loaded via NODE_OPTIONS for pi RPC runtimes.
// Serializes stdout/stderr writes and retries transient ENOBUFS errors so a burst of
// RPC events cannot crash the pi node process with an unhandled Socket error.
(() => {
  const RETRYABLE = new Set(["ENOBUFS", "EAGAIN", "EWOULDBLOCK"]);
  for (const stream of [process.stdout, process.stderr]) installGuard(stream);

  function installGuard(stream) {
    if (!stream || stream.__boxedagentRpcStdioGuard) return;
    Object.defineProperty(stream, "__boxedagentRpcStdioGuard", { value: true });
    const originalWrite = stream.write.bind(stream);
    const queue = [];
    let writing = false;
    let closed = false;

    stream.on("error", (err) => {
      if (err && (RETRYABLE.has(err.code) || err.code === "EPIPE")) {
        if (err.code === "EPIPE") closed = true;
        return;
      }
      throw err;
    });

    stream.write = function guardedWrite(chunk, encoding, callback) {
      if (typeof encoding === "function") {
        callback = encoding;
        encoding = undefined;
      }
      if (closed) {
        if (typeof callback === "function") queueMicrotask(() => callback());
        return false;
      }
      queue.push({ chunk, encoding, callback });
      pump();
      return queue.length < 1024;
    };

    function pump() {
      if (writing || closed) return;
      const item = queue.shift();
      if (!item) return;
      writing = true;
      let settled = false;
      const done = (err) => {
        if (settled) return;
        settled = true;
        writing = false;
        if (err) {
          if (RETRYABLE.has(err.code)) {
            queue.unshift(item);
            setTimeout(pump, 25);
            return;
          }
          if (err.code === "EPIPE") closed = true;
        }
        if (typeof item.callback === "function") item.callback(err);
        setImmediate(pump);
      };
      try {
        originalWrite(item.chunk, item.encoding, done);
      } catch (err) {
        done(err);
      }
    }
  }
})();
`;

async function writeOrRemove(file: string, content?: string) {
  if (content && content.trim().length > 0) {
    await fs.ensureDir(path.dirname(file));
    await fs.writeFile(file, content, "utf8");
  } else {
    await fs.remove(file);
  }
}

export function hostPathForContainerWorkspacePath(box: BoxRecord, containerPath?: string): string | undefined {
  if (!containerPath) return undefined;
  if (!containerPath.startsWith("/workspace")) return undefined;
  const rel = containerPath.slice("/workspace".length).replace(/^\/+/, "");
  return path.join(box.workspacePath, rel);
}
